version: '3.5'

services:
  neo:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - 'neo_data:/data'
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]

volumes:
  neo_data:
